export const games = [
    {
        id: 401411124,
        season: 2022,
        week: 5,
        season_type: 'regular',
        start_date: '2022-10-01T16:00:00.000Z',
        start_time_tbd: false,
        neutral_site: false,
        conference_game: true,
        attendance: null,
        venue_id: 3615,
        venue: 'Alumni Stadium',
        home_id: 103,
        home_team: 'Boston College',
        home_conference: 'ACC',
        home_division: 'fbs',
        home_points: null,
        home_line_scores: null,
        home_post_win_prob: null,
        home_pregame_elo: 1332,
        home_postgame_elo: null,
        away_id: 97,
        away_team: 'Louisville',
        away_conference: 'ACC',
        away_division: 'fbs',
        away_points: null,
        away_line_scores: null,
        away_post_win_prob: null,
        away_pregame_elo: 1575,
        away_postgame_elo: null,
        excitement_index: null,
        highlights: null,
        notes: null
    },
    {
        id: 401411127,
        season: 2022,
        week: 5,
        season_type: 'regular',
        start_date: '2022-10-01T19:30:00.000Z',
        start_time_tbd: false,
        neutral_site: false,
        conference_game: true,
        attendance: null,
        venue_id: 3697,
        venue: 'Bobby Bowden Field at Doak Campbell Stadium',
        home_id: 52,
        home_team: 'Florida State',
        home_conference: 'ACC',
        home_division: 'fbs',
        home_points: null,
        home_line_scores: null,
        home_post_win_prob: null,
        home_pregame_elo: 1577,
        home_postgame_elo: null,
        away_id: 154,
        away_team: 'Wake Forest',
        away_conference: 'ACC',
        away_division: 'fbs',
        away_points: null,
        away_line_scores: null,
        away_post_win_prob: null,
        away_pregame_elo: 1666,
        away_postgame_elo: null,
        excitement_index: null,
        highlights: null,
        notes: null
    },
    {
        id: 401411128,
        season: 2022,
        week: 5,
        season_type: 'regular',
        start_date: '2022-10-01T19:30:00.000Z',
        start_time_tbd: false,
        neutral_site: false,
        conference_game: true,
        attendance: null,
        venue_id: 3787,
        venue: 'Kenan Memorial Stadium',
        home_id: 153,
        home_team: 'North Carolina',
        home_conference: 'ACC',
        home_division: 'fbs',
        home_points: null,
        home_line_scores: null,
        home_post_win_prob: null,
        home_pregame_elo: 1559,
        home_postgame_elo: null,
        away_id: 259,
        away_team: 'Virginia Tech',
        away_conference: 'ACC',
        away_division: 'fbs',
        away_points: null,
        away_line_scores: null,
        away_post_win_prob: null,
        away_pregame_elo: 1388,
        away_postgame_elo: null,
        excitement_index: null,
        highlights: null,
        notes: null
    },
    {
        id: 401411130,
        season: 2022,
        week: 5,
        season_type: 'regular',
        start_date: '2022-10-01T21:00:00.000Z',
        start_time_tbd: false,
        neutral_site: false,
        conference_game: false,
        attendance: null,
        venue_id: 1964,
        venue: 'Carrier Dome',
        home_id: 183,
        home_team: 'Syracuse',
        home_conference: 'ACC',
        home_division: 'fbs',
        home_points: null,
        home_line_scores: null,
        home_post_win_prob: null,
        home_pregame_elo: 1539,
        home_postgame_elo: 1539,
        away_id: 2681,
        away_team: 'Wagner',
        away_conference: 'NEC',
        away_division: 'fcs',
        away_points: null,
        away_line_scores: null,
        away_post_win_prob: null,
        away_pregame_elo: null,
        away_postgame_elo: null,
        excitement_index: null,
        highlights: null,
        notes: null
    },
    {
        id: 401411126,
        season: 2022,
        week: 5,
        season_type: 'regular',
        start_date: '2022-10-01T23:30:00.000Z',
        start_time_tbd: false,
        neutral_site: false,
        conference_game: true,
        attendance: null,
        venue_id: 3982,
        venue: 'Wallace Wade Stadium',
        home_id: 150,
        home_team: 'Duke',
        home_conference: 'ACC',
        home_division: 'fbs',
        home_points: null,
        home_line_scores: null,
        home_post_win_prob: null,
        home_pregame_elo: 1261,
        home_postgame_elo: null,
        away_id: 258,
        away_team: 'Virginia',
        away_conference: 'ACC',
        away_division: 'fbs',
        away_points: null,
        away_line_scores: null,
        away_post_win_prob: null,
        away_pregame_elo: 1481,
        away_postgame_elo: null,
        excitement_index: null,
        highlights: null,
        notes: null
    },
    {
        id: 401411125,
        season: 2022,
        week: 5,
        season_type: 'regular',
        start_date: '2022-10-01T23:30:00.000Z',
        start_time_tbd: false,
        neutral_site: false,
        conference_game: true,
        attendance: null,
        venue_id: 3836,
        venue: 'Memorial Stadium',
        home_id: 228,
        home_team: 'Clemson',
        home_conference: 'ACC',
        home_division: 'fbs',
        home_points: null,
        home_line_scores: null,
        home_post_win_prob: null,
        home_pregame_elo: 1809,
        home_postgame_elo: null,
        away_id: 152,
        away_team: 'NC State',
        away_conference: 'ACC',
        away_division: 'fbs',
        away_points: null,
        away_line_scores: null,
        away_post_win_prob: null,
        away_pregame_elo: 1659,
        away_postgame_elo: null,
        excitement_index: null,
        highlights: null,
        notes: null
    },
    {
        id: 401411129,
        season: 2022,
        week: 5,
        season_type: 'regular',
        start_date: '2022-10-02T00:00:00.000Z',
        start_time_tbd: false,
        neutral_site: false,
        conference_game: true,
        attendance: null,
        venue_id: 3752,
        venue: 'Heinz Field',
        home_id: 221,
        home_team: 'Pittsburgh',
        home_conference: 'ACC',
        home_division: 'fbs',
        home_points: null,
        home_line_scores: null,
        home_post_win_prob: null,
        home_pregame_elo: 1695,
        home_postgame_elo: null,
        away_id: 59,
        away_team: 'Georgia Tech',
        away_conference: 'ACC',
        away_division: 'fbs',
        away_points: null,
        away_line_scores: null,
        away_post_win_prob: null,
        away_pregame_elo: 1235,
        away_postgame_elo: null,
        excitement_index: null,
        highlights: null,
        notes: null
    }
];
  